env:
  global:
    - CC_TEST_REPORTER_ID=c044d220e12198a9d97d568cbe445e5588c5c05fff728b9e45c833b0c9af7825

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  python -m unittest discover tests

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT